#!/usr/bin/env bash
set -exuo pipefail

function add_peer_to_server() {
  local config_name="$1"
  local client_cidr="$2"
  local client_public_key_name="$3"

  stat "/etc/wireguard/${client_public_key_name}"
  local client_public_key=$(cat "/etc/wireguard/${client_public_key_name}")

  local addition="$(cat << EOF

[Peer] # $client_cidr
PublicKey = $client_public_key
AllowedIPs = $client_cidr
EOF
)"
  echo "$addition" >> "/etc/wireguard/${config_name}.conf"
}

function main() {
  set +u
  while true; do
    case "$1" in
      --config-name              ) CONFIG_NAME=$2; shift 2 ;;
      --client-cidr             ) CLIENT_CIDR=$2; shift 2 ;;
      --client-public-key-name  ) PUBLIC_KEY_NAME=$2; shift 2 ;;
      -- ) shift; break ;;
    * ) break ;;
    esac
  done
  set -u

  add_peer_to_server "$CONFIG_NAME" "$CLIENT_CIDR" "$PUBLIC_KEY_NAME"
  wg syncconf "$CONFIG_NAME" <(wg-quick strip "$CONFIG_NAME")
  wg-quick down "$CONFIG_NAME"
  wg-quick up "$CONFIG_NAME"
}
main "$@"