#!/usr/bin/env bash
set -exu

function add_network() {
  local network_cidr="$1"

  iptables -I OUTPUT -d "$network_cidr" -j ACCEPT
  iptables -I INPUT -s "$network_cidr" -j ACCEPT
  iptables -t nat -A POSTROUTING -s "$network_cidr" -o eth0 -j MASQUERADE
  iptables-save > /etc/iptables/rules.v4
  rc-service iptables restart
}

function remove_network() {
  local network_cidr="$1"
  iptables -D OUTPUT -d "$network_cidr" -j ACCEPT
  iptables -D INPUT -s "$network_cidr" -j ACCEPT
  iptables -t nat -D POSTROUTING -s "$network_cidr" -o eth0 -j MASQUERADE
  iptables-save > /etc/iptables/rules.v4
  rc-service iptables restart
}

function main() {
  local add="add-network"
  local remove="remove-network"

  set +u
  while true; do
    case "$1" in
      --operation          ) OPERATION=$2; shift 2 ;;
      --network-cidr       ) NETWORK_CIDR=$2; shift 2 ;;
      -- ) shift; break ;;
    * ) break ;;
    esac
  done

  case "$OPERATION" in
    "$add")
      : ;;
    "$remove")
      : ;;
    *) echo "invalid operation, choose from [${add}, ${remove}]" && exit 1
  esac
  set -u

  if [[ "$OPERATION" == "$add" ]]; then
    add_network "$NETWORK_CIDR"
  elif [[ "$OPERATION" == "$remove" ]]; then
    remove_network "$NETWORK_CIDR"
  fi
}
main "$@"