#!/usr/bin/env bash
set -exuo pipefail

function create_config() {
  local config_name="$1"
  local server_cidr="$2"
  local listen_port="$3"
  local private_key_name="$4"

  stat "/etc/wireguard/${private_key_name}"
  local private_key=$(cat "/etc/wireguard/${private_key_name}")

  config=$(cat << EOF
[Interface]
Address = $server_cidr
ListenPort = $listen_port
PrivateKey = $private_key
EOF
)
  echo "$config" > "/etc/wireguard/${config_name}.conf"
}

function main() {
  set +u
  while true; do
    case "$1" in
      --config-name       ) CONFIG_NAME=$2; shift 2 ;;
      --server-cidr      ) SERVER_CIDR=$2; shift 2 ;;
      --listen-port      ) LISTEN_PORT=$2; shift 2 ;;
      --private-key-name ) PRIVATE_KEY_NAME=$2; shift 2 ;;
      -- ) shift; break ;;
    * ) break ;;
    esac
  done
  set -u

  create_config "$CONFIG_NAME" "$SERVER_CIDR" "$LISTEN_PORT" "$PRIVATE_KEY_NAME"
}
main "$@"
