#!/usr/bin/env bash
set -exuo pipefail

function create_client_config() {
  local config_name="$1"
  local client_private_key_name="$2"
  local client_cidr="$3"
  local client_dns="$4"
  local network_public_key_name="$5"
  local network_endpoint="$6"
  local network_listen_port="$7"
  local allowed_ips="$8"

  stat "$client_private_key_name"
  local client_private_key=$(cat "$client_private_key_name")

  stat "$network_public_key_name"
  local server_public_key=$(cat "$network_public_key_name")


  local config="$(cat << EOF
[Interface]
PrivateKey = $client_private_key
Address = $client_cidr
DNS = $client_dns
[Peer]
PublicKey = $server_public_key
Endpoint = $network_endpoint:$network_listen_port
AllowedIPs = $allowed_ips
EOF
)"
echo "$config" > "$config_name"
}

function main() {
  set +u
  while true; do
    case "$1" in
      --config-name              ) CONFIG_NAME=$2; shift 2 ;;
      --client-private-key-name ) CLIENT_PRIVATE_KEY_NAME=$2; shift 2 ;;
      --client-cidr             ) CLIENT_CIDR=$2; shift 2 ;;
      --client-dns              ) CLIENT_DNS=$2; shift 2 ;;
      --network-public-key-name ) NETWORK_PUBLIC_KEY_NAME=$2; shift 2;;
      --network-endpoint        ) NETWORK_ENDPOINT=$2; shift 2 ;;
      --network-listen-port     ) NETWORK_LISTEN_PORT=$2; shift 2 ;;
      --allowed-ips             ) ALLOWED_IPS=$2; shift 2 ;;
      -- ) shift; break ;;
    * ) break ;;
    esac
  done
  set -u

  create_client_config "$CONFIG_NAME" "$CLIENT_PRIVATE_KEY_NAME" "$CLIENT_CIDR" "$CLIENT_DNS" "$NETWORK_PUBLIC_KEY_NAME" "$NETWORK_ENDPOINT" "$NETWORK_LISTEN_PORT" "$ALLOWED_IPS"
}
main "$@"