#!/usr/bin/env bash
set -exuo pipefail

function create_config() {
  local config_name="$1"
  local network_cidr="$2"
  local network_listen_port="$3"
  local network_private_key_name="$4"

  stat "$network_private_key_name"
  local private_key=$(cat "$network_private_key_name")

  config=$(cat << EOF
[Interface]
Address = $network_cidr
ListenPort = $network_listen_port
PrivateKey = $private_key
EOF
)
  echo "$config" > "$config_name"
}

function main() {
  set +u
  while true; do
    case "$1" in
      --config-name               ) CONFIG_NAME=$2; shift 2 ;;
      --network-cidr             ) NETWORK_CIDR=$2; shift 2 ;;
      --network-listen-port      ) NETWORK_LISTEN_PORT=$2; shift 2 ;;
      --network-private-key-name ) NETWORK_PRIVATE_KEY_NAME=$2; shift 2 ;;
      -- ) shift; break ;;
    * ) break ;;
    esac
  done
  set -u

  create_config "$CONFIG_NAME" "$NETWORK_CIDR" "$NETWORK_LISTEN_PORT" "$NETWORK_PRIVATE_KEY_NAME"
}
main "$@"
