#!/usr/bin/env bash
set -exuo pipefail

function create_pair() {
  local privkey_name="$1"
  local pubkey_name="$2"

  umask 077; wg genkey | tee "$privkey_name" | wg pubkey > "$pubkey_name"
}

function main() {
  set +u
  while true; do
    case "$1" in
      --private-key-name   ) PRIVKEYNAME=$2; shift 2 ;;
      --public-key-name    ) PUBKEYNAME=$2; shift 2 ;;
      -- ) shift; break ;;
    * ) break ;;
    esac
  done
  set -u

  cd /etc/wireguard
  create_pair "$PRIVKEYNAME" "$PUBKEYNAME"
}
main "$@"
