/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateStartRequest
 */
export interface AuthenticateStartRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateStartRequest
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateStartRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthenticateStartRequest interface.
 */
export function instanceOfAuthenticateStartRequest(value: object): value is AuthenticateStartRequest {
    return true;
}

export function AuthenticateStartRequestFromJSON(json: any): AuthenticateStartRequest {
    return AuthenticateStartRequestFromJSONTyped(json, false);
}

export function AuthenticateStartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateStartRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthenticateStartRequestToJSON(json: any): AuthenticateStartRequest {
    return AuthenticateStartRequestToJSONTyped(json, false);
}

export function AuthenticateStartRequestToJSONTyped(value?: AuthenticateStartRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'password': value['password'],
    };
}

