/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateStartResponse
 */
export interface AuthenticateStartResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticateStartResponse
     */
    twoFactorRequired?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthenticateStartResponse
     */
    allowedSecondFactors?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof AuthenticateStartResponse
     */
    challengeExpiresAt?: Date;
}

/**
 * Check if a given object implements the AuthenticateStartResponse interface.
 */
export function instanceOfAuthenticateStartResponse(value: object): value is AuthenticateStartResponse {
    return true;
}

export function AuthenticateStartResponseFromJSON(json: any): AuthenticateStartResponse {
    return AuthenticateStartResponseFromJSONTyped(json, false);
}

export function AuthenticateStartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateStartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'twoFactorRequired': json['twoFactorRequired'] == null ? undefined : json['twoFactorRequired'],
        'allowedSecondFactors': json['allowedSecondFactors'] == null ? undefined : json['allowedSecondFactors'],
        'challengeExpiresAt': json['challengeExpiresAt'] == null ? undefined : (new Date(json['challengeExpiresAt'])),
    };
}

export function AuthenticateStartResponseToJSON(json: any): AuthenticateStartResponse {
    return AuthenticateStartResponseToJSONTyped(json, false);
}

export function AuthenticateStartResponseToJSONTyped(value?: AuthenticateStartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'twoFactorRequired': value['twoFactorRequired'],
        'allowedSecondFactors': value['allowedSecondFactors'],
        'challengeExpiresAt': value['challengeExpiresAt'] == null ? undefined : ((value['challengeExpiresAt']).toISOString()),
    };
}

