/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Client
 */
export interface Client {
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    clientName?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    clientPrivateKeyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    clientPublicKeyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    clientPublicKeyValue?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    clientCidr?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    clientDns?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    allowedIps?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    networkPublicKeyName?: string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    networkEndpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof Client
     */
    networkListenPort?: number;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    clientTag?: string;
}

/**
 * Check if a given object implements the Client interface.
 */
export function instanceOfClient(value: object): value is Client {
    return true;
}

export function ClientFromJSON(json: any): Client {
    return ClientFromJSONTyped(json, false);
}

export function ClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Client {
    if (json == null) {
        return json;
    }
    return {
        
        'clientName': json['clientName'] == null ? undefined : json['clientName'],
        'clientPrivateKeyName': json['clientPrivateKeyName'] == null ? undefined : json['clientPrivateKeyName'],
        'clientPublicKeyName': json['clientPublicKeyName'] == null ? undefined : json['clientPublicKeyName'],
        'clientPublicKeyValue': json['clientPublicKeyValue'] == null ? undefined : json['clientPublicKeyValue'],
        'clientCidr': json['clientCidr'] == null ? undefined : json['clientCidr'],
        'clientDns': json['clientDns'] == null ? undefined : json['clientDns'],
        'allowedIps': json['allowedIps'] == null ? undefined : json['allowedIps'],
        'networkPublicKeyName': json['networkPublicKeyName'] == null ? undefined : json['networkPublicKeyName'],
        'networkEndpoint': json['networkEndpoint'] == null ? undefined : json['networkEndpoint'],
        'networkListenPort': json['networkListenPort'] == null ? undefined : json['networkListenPort'],
        'clientTag': json['clientTag'] == null ? undefined : json['clientTag'],
    };
}

export function ClientToJSON(json: any): Client {
    return ClientToJSONTyped(json, false);
}

export function ClientToJSONTyped(value?: Client | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientName': value['clientName'],
        'clientPrivateKeyName': value['clientPrivateKeyName'],
        'clientPublicKeyName': value['clientPublicKeyName'],
        'clientPublicKeyValue': value['clientPublicKeyValue'],
        'clientCidr': value['clientCidr'],
        'clientDns': value['clientDns'],
        'allowedIps': value['allowedIps'],
        'networkPublicKeyName': value['networkPublicKeyName'],
        'networkEndpoint': value['networkEndpoint'],
        'networkListenPort': value['networkListenPort'],
        'clientTag': value['clientTag'],
    };
}

