/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetNextAvailableClientAddressResponse
 */
export interface GetNextAvailableClientAddressResponse {
    /**
     * 
     * @type {string}
     * @memberof GetNextAvailableClientAddressResponse
     */
    nextAvailableAddress?: string;
}

/**
 * Check if a given object implements the GetNextAvailableClientAddressResponse interface.
 */
export function instanceOfGetNextAvailableClientAddressResponse(value: object): value is GetNextAvailableClientAddressResponse {
    return true;
}

export function GetNextAvailableClientAddressResponseFromJSON(json: any): GetNextAvailableClientAddressResponse {
    return GetNextAvailableClientAddressResponseFromJSONTyped(json, false);
}

export function GetNextAvailableClientAddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNextAvailableClientAddressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextAvailableAddress': json['nextAvailableAddress'] == null ? undefined : json['nextAvailableAddress'],
    };
}

export function GetNextAvailableClientAddressResponseToJSON(json: any): GetNextAvailableClientAddressResponse {
    return GetNextAvailableClientAddressResponseToJSONTyped(json, false);
}

export function GetNextAvailableClientAddressResponseToJSONTyped(value?: GetNextAvailableClientAddressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextAvailableAddress': value['nextAvailableAddress'],
    };
}

