/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNetworksRequest
 */
export interface ListNetworksRequest {
    /**
     * 
     * @type {number}
     * @memberof ListNetworksRequest
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ListNetworksRequest
     */
    maxItems?: number;
}

/**
 * Check if a given object implements the ListNetworksRequest interface.
 */
export function instanceOfListNetworksRequest(value: object): value is ListNetworksRequest {
    return true;
}

export function ListNetworksRequestFromJSON(json: any): ListNetworksRequest {
    return ListNetworksRequestFromJSONTyped(json, false);
}

export function ListNetworksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNetworksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'maxItems': json['maxItems'] == null ? undefined : json['maxItems'],
    };
}

export function ListNetworksRequestToJSON(json: any): ListNetworksRequest {
    return ListNetworksRequestToJSONTyped(json, false);
}

export function ListNetworksRequestToJSONTyped(value?: ListNetworksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'maxItems': value['maxItems'],
    };
}

