/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNetworkClientsRequest
 */
export interface ListNetworkClientsRequest {
    /**
     * 
     * @type {string}
     * @memberof ListNetworkClientsRequest
     */
    clientName?: string;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkClientsRequest
     */
    networkName: string;
}

/**
 * Check if a given object implements the ListNetworkClientsRequest interface.
 */
export function instanceOfListNetworkClientsRequest(value: object): value is ListNetworkClientsRequest {
    if (!('networkName' in value) || value['networkName'] === undefined) return false;
    return true;
}

export function ListNetworkClientsRequestFromJSON(json: any): ListNetworkClientsRequest {
    return ListNetworkClientsRequestFromJSONTyped(json, false);
}

export function ListNetworkClientsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNetworkClientsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientName': json['clientName'] == null ? undefined : json['clientName'],
        'networkName': json['networkName'],
    };
}

export function ListNetworkClientsRequestToJSON(json: any): ListNetworkClientsRequest {
    return ListNetworkClientsRequestToJSONTyped(json, false);
}

export function ListNetworkClientsRequestToJSONTyped(value?: ListNetworkClientsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientName': value['clientName'],
        'networkName': value['networkName'],
    };
}

