/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegenerateRecoveryCodesResponse
 */
export interface RegenerateRecoveryCodesResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof RegenerateRecoveryCodesResponse
     */
    codes?: Array<string>;
}

/**
 * Check if a given object implements the RegenerateRecoveryCodesResponse interface.
 */
export function instanceOfRegenerateRecoveryCodesResponse(value: object): value is RegenerateRecoveryCodesResponse {
    return true;
}

export function RegenerateRecoveryCodesResponseFromJSON(json: any): RegenerateRecoveryCodesResponse {
    return RegenerateRecoveryCodesResponseFromJSONTyped(json, false);
}

export function RegenerateRecoveryCodesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegenerateRecoveryCodesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'codes': json['codes'] == null ? undefined : json['codes'],
    };
}

export function RegenerateRecoveryCodesResponseToJSON(json: any): RegenerateRecoveryCodesResponse {
    return RegenerateRecoveryCodesResponseToJSONTyped(json, false);
}

export function RegenerateRecoveryCodesResponseToJSONTyped(value?: RegenerateRecoveryCodesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'codes': value['codes'],
    };
}

