/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamClientConnectionInfoRequest
 */
export interface StreamClientConnectionInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof StreamClientConnectionInfoRequest
     */
    clientPublicKeyValue?: string;
}

/**
 * Check if a given object implements the StreamClientConnectionInfoRequest interface.
 */
export function instanceOfStreamClientConnectionInfoRequest(value: object): value is StreamClientConnectionInfoRequest {
    return true;
}

export function StreamClientConnectionInfoRequestFromJSON(json: any): StreamClientConnectionInfoRequest {
    return StreamClientConnectionInfoRequestFromJSONTyped(json, false);
}

export function StreamClientConnectionInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamClientConnectionInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientPublicKeyValue': json['clientPublicKeyValue'] == null ? undefined : json['clientPublicKeyValue'],
    };
}

export function StreamClientConnectionInfoRequestToJSON(json: any): StreamClientConnectionInfoRequest {
    return StreamClientConnectionInfoRequestToJSONTyped(json, false);
}

export function StreamClientConnectionInfoRequestToJSONTyped(value?: StreamClientConnectionInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientPublicKeyValue': value['clientPublicKeyValue'],
    };
}

