/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamNetworkConnectionInfoRequest
 */
export interface StreamNetworkConnectionInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof StreamNetworkConnectionInfoRequest
     */
    networkPublicKeyValue?: string;
}

/**
 * Check if a given object implements the StreamNetworkConnectionInfoRequest interface.
 */
export function instanceOfStreamNetworkConnectionInfoRequest(value: object): value is StreamNetworkConnectionInfoRequest {
    return true;
}

export function StreamNetworkConnectionInfoRequestFromJSON(json: any): StreamNetworkConnectionInfoRequest {
    return StreamNetworkConnectionInfoRequestFromJSONTyped(json, false);
}

export function StreamNetworkConnectionInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamNetworkConnectionInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'networkPublicKeyValue': json['networkPublicKeyValue'] == null ? undefined : json['networkPublicKeyValue'],
    };
}

export function StreamNetworkConnectionInfoRequestToJSON(json: any): StreamNetworkConnectionInfoRequest {
    return StreamNetworkConnectionInfoRequestToJSONTyped(json, false);
}

export function StreamNetworkConnectionInfoRequestToJSONTyped(value?: StreamNetworkConnectionInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networkPublicKeyValue': value['networkPublicKeyValue'],
    };
}

