/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotpEnrollConfirmRequest
 */
export interface TotpEnrollConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof TotpEnrollConfirmRequest
     */
    otpCode?: string;
}

/**
 * Check if a given object implements the TotpEnrollConfirmRequest interface.
 */
export function instanceOfTotpEnrollConfirmRequest(value: object): value is TotpEnrollConfirmRequest {
    return true;
}

export function TotpEnrollConfirmRequestFromJSON(json: any): TotpEnrollConfirmRequest {
    return TotpEnrollConfirmRequestFromJSONTyped(json, false);
}

export function TotpEnrollConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotpEnrollConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'otpCode': json['otpCode'] == null ? undefined : json['otpCode'],
    };
}

export function TotpEnrollConfirmRequestToJSON(json: any): TotpEnrollConfirmRequest {
    return TotpEnrollConfirmRequestToJSONTyped(json, false);
}

export function TotpEnrollConfirmRequestToJSONTyped(value?: TotpEnrollConfirmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otpCode': value['otpCode'],
    };
}

