/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotpEnrollStartResponse
 */
export interface TotpEnrollStartResponse {
    /**
     * 
     * @type {string}
     * @memberof TotpEnrollStartResponse
     */
    issuer?: string;
    /**
     * 
     * @type {string}
     * @memberof TotpEnrollStartResponse
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof TotpEnrollStartResponse
     */
    manualEntryKey?: string;
    /**
     * 
     * @type {string}
     * @memberof TotpEnrollStartResponse
     */
    otpauthUri?: string;
}

/**
 * Check if a given object implements the TotpEnrollStartResponse interface.
 */
export function instanceOfTotpEnrollStartResponse(value: object): value is TotpEnrollStartResponse {
    return true;
}

export function TotpEnrollStartResponseFromJSON(json: any): TotpEnrollStartResponse {
    return TotpEnrollStartResponseFromJSONTyped(json, false);
}

export function TotpEnrollStartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotpEnrollStartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'issuer': json['issuer'] == null ? undefined : json['issuer'],
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'manualEntryKey': json['manualEntryKey'] == null ? undefined : json['manualEntryKey'],
        'otpauthUri': json['otpauthUri'] == null ? undefined : json['otpauthUri'],
    };
}

export function TotpEnrollStartResponseToJSON(json: any): TotpEnrollStartResponse {
    return TotpEnrollStartResponseToJSONTyped(json, false);
}

export function TotpEnrollStartResponseToJSONTyped(value?: TotpEnrollStartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuer': value['issuer'],
        'accountName': value['accountName'],
        'manualEntryKey': value['manualEntryKey'],
        'otpauthUri': value['otpauthUri'],
    };
}

