/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateNetworkRequest
 */
export interface UpdateNetworkRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateNetworkRequest
     */
    networkTag?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateNetworkRequest
     */
    networkStatus?: UpdateNetworkRequestNetworkStatusEnum;
}


/**
 * @export
 */
export const UpdateNetworkRequestNetworkStatusEnum = {
    Created: 'CREATED',
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Deleted: 'DELETED'
} as const;
export type UpdateNetworkRequestNetworkStatusEnum = typeof UpdateNetworkRequestNetworkStatusEnum[keyof typeof UpdateNetworkRequestNetworkStatusEnum];


/**
 * Check if a given object implements the UpdateNetworkRequest interface.
 */
export function instanceOfUpdateNetworkRequest(value: object): value is UpdateNetworkRequest {
    return true;
}

export function UpdateNetworkRequestFromJSON(json: any): UpdateNetworkRequest {
    return UpdateNetworkRequestFromJSONTyped(json, false);
}

export function UpdateNetworkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNetworkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'networkTag': json['networkTag'] == null ? undefined : json['networkTag'],
        'networkStatus': json['networkStatus'] == null ? undefined : json['networkStatus'],
    };
}

export function UpdateNetworkRequestToJSON(json: any): UpdateNetworkRequest {
    return UpdateNetworkRequestToJSONTyped(json, false);
}

export function UpdateNetworkRequestToJSONTyped(value?: UpdateNetworkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networkTag': value['networkTag'],
        'networkStatus': value['networkStatus'],
    };
}

