/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    twoFactorEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    twoFactorMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    totpSecretEncrypted?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    totpEnabledAt?: Date;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'password': json['password'] == null ? undefined : json['password'],
        'twoFactorEnabled': json['twoFactorEnabled'] == null ? undefined : json['twoFactorEnabled'],
        'twoFactorMethod': json['twoFactorMethod'] == null ? undefined : json['twoFactorMethod'],
        'totpSecretEncrypted': json['totpSecretEncrypted'] == null ? undefined : json['totpSecretEncrypted'],
        'totpEnabledAt': json['totpEnabledAt'] == null ? undefined : (new Date(json['totpEnabledAt'])),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'password': value['password'],
        'twoFactorEnabled': value['twoFactorEnabled'],
        'twoFactorMethod': value['twoFactorMethod'],
        'totpSecretEncrypted': value['totpSecretEncrypted'],
        'totpEnabledAt': value['totpEnabledAt'] == null ? undefined : ((value['totpEnabledAt']).toISOString()),
    };
}

