/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRecoveryCodeRequest
 */
export interface VerifyRecoveryCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifyRecoveryCodeRequest
     */
    recoveryCode?: string;
}

/**
 * Check if a given object implements the VerifyRecoveryCodeRequest interface.
 */
export function instanceOfVerifyRecoveryCodeRequest(value: object): value is VerifyRecoveryCodeRequest {
    return true;
}

export function VerifyRecoveryCodeRequestFromJSON(json: any): VerifyRecoveryCodeRequest {
    return VerifyRecoveryCodeRequestFromJSONTyped(json, false);
}

export function VerifyRecoveryCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRecoveryCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recoveryCode': json['recoveryCode'] == null ? undefined : json['recoveryCode'],
    };
}

export function VerifyRecoveryCodeRequestToJSON(json: any): VerifyRecoveryCodeRequest {
    return VerifyRecoveryCodeRequestToJSONTyped(json, false);
}

export function VerifyRecoveryCodeRequestToJSONTyped(value?: VerifyRecoveryCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recoveryCode': value['recoveryCode'],
    };
}

