/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VerifyTotpRequest
 */
export interface VerifyTotpRequest {
    /**
     *
     * @type {string}
     * @memberof VerifyTotpRequest
     */
    otpCode?: string;
}

/**
 * Check if a given object implements the VerifyTotpRequest interface.
 */
export function instanceOfVerifyTotpRequest(value: object): value is VerifyTotpRequest {
    return true;
}

export function VerifyTotpRequestFromJSON(json: any): VerifyTotpRequest {
    return VerifyTotpRequestFromJSONTyped(json, false);
}

export function VerifyTotpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyTotpRequest {
    if (json == null) {
        return json;
    }
    return {

        'otpCode': json['otpCode'] == null ? undefined : json['otpCode'],
    };
}

export function VerifyTotpRequestToJSON(json: any): VerifyTotpRequest {
    return VerifyTotpRequestToJSONTyped(json, false);
}

export function VerifyTotpRequestToJSONTyped(value?: VerifyTotpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'otpCode': value['otpCode'],
    };
}

