/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WhoamiResponse
 */
export interface WhoamiResponse {
    /**
     * 
     * @type {string}
     * @memberof WhoamiResponse
     */
    user?: string;
}

/**
 * Check if a given object implements the WhoamiResponse interface.
 */
export function instanceOfWhoamiResponse(value: object): value is WhoamiResponse {
    return true;
}

export function WhoamiResponseFromJSON(json: any): WhoamiResponse {
    return WhoamiResponseFromJSONTyped(json, false);
}

export function WhoamiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhoamiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function WhoamiResponseToJSON(json: any): WhoamiResponse {
    return WhoamiResponseToJSONTyped(json, false);
}

export function WhoamiResponseToJSONTyped(value?: WhoamiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
    };
}

