/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SseEmitter,
  StreamClientConnectionInfoRequest,
  StreamNetworkConnectionInfoRequest,
} from '../models/index';
import {
    SseEmitterFromJSON,
    SseEmitterToJSON,
    StreamClientConnectionInfoRequestFromJSON,
    StreamClientConnectionInfoRequestToJSON,
    StreamNetworkConnectionInfoRequestFromJSON,
    StreamNetworkConnectionInfoRequestToJSON,
} from '../models/index';

export interface StreamClientConnectionInfoOperationRequest {
    streamClientConnectionInfoRequest: StreamClientConnectionInfoRequest;
}

export interface StreamNetworkConnectionInfoOperationRequest {
    streamNetworkConnectionInfoRequest: StreamNetworkConnectionInfoRequest;
}

/**
 * 
 */
export class SystemControllerApi extends runtime.BaseAPI {

    /**
     * Server-Sent Events endpoint that streams real-time WireGuard connection data for a specific client/peer
     * Stream Client WireGuard Information
     */
    async streamClientConnectionInfoRaw(requestParameters: StreamClientConnectionInfoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SseEmitter>> {
        if (requestParameters['streamClientConnectionInfoRequest'] == null) {
            throw new runtime.RequiredError(
                'streamClientConnectionInfoRequest',
                'Required parameter "streamClientConnectionInfoRequest" was null or undefined when calling streamClientConnectionInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/system/wg-show/client`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StreamClientConnectionInfoRequestToJSON(requestParameters['streamClientConnectionInfoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SseEmitterFromJSON(jsonValue));
    }

    /**
     * Server-Sent Events endpoint that streams real-time WireGuard connection data for a specific client/peer
     * Stream Client WireGuard Information
     */
    async streamClientConnectionInfo(requestParameters: StreamClientConnectionInfoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SseEmitter> {
        const response = await this.streamClientConnectionInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Server-Sent Events endpoint that streams real-time WireGuard connection data for a specific network and its peers
     * Stream Network WireGuard Information
     */
    async streamNetworkConnectionInfoRaw(requestParameters: StreamNetworkConnectionInfoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SseEmitter>> {
        if (requestParameters['streamNetworkConnectionInfoRequest'] == null) {
            throw new runtime.RequiredError(
                'streamNetworkConnectionInfoRequest',
                'Required parameter "streamNetworkConnectionInfoRequest" was null or undefined when calling streamNetworkConnectionInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/system/wg-show/network`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StreamNetworkConnectionInfoRequestToJSON(requestParameters['streamNetworkConnectionInfoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SseEmitterFromJSON(jsonValue));
    }

    /**
     * Server-Sent Events endpoint that streams real-time WireGuard connection data for a specific network and its peers
     * Stream Network WireGuard Information
     */
    async streamNetworkConnectionInfo(requestParameters: StreamNetworkConnectionInfoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SseEmitter> {
        const response = await this.streamNetworkConnectionInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
