/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetPublicIpResponse,
} from '../models/index';
import {
    GetPublicIpResponseFromJSON,
    GetPublicIpResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class ToolControllerApi extends runtime.BaseAPI {

    /**
     * get the server\'s public IP address
     * Get Public IP
     */
    async getPublicIpRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPublicIpResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/tools/public-ip`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPublicIpResponseFromJSON(jsonValue));
    }

    /**
     * get the server\'s public IP address
     * Get Public IP
     */
    async getPublicIp(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPublicIpResponse> {
        const response = await this.getPublicIpRaw(initOverrides);
        return await response.value();
    }

}
