/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthenticateStartRequest,
  AuthenticateStartResponse,
  RegenerateRecoveryCodesResponse,
  TotpEnrollConfirmRequest,
  TotpEnrollStartResponse,
  User,
  VerifyRecoveryCodeRequest,
  VerifyTotpRequest,
  WhoamiResponse,
} from '../models/index';
import {
    AuthenticateStartRequestFromJSON,
    AuthenticateStartRequestToJSON,
    AuthenticateStartResponseFromJSON,
    AuthenticateStartResponseToJSON,
    RegenerateRecoveryCodesResponseFromJSON,
    RegenerateRecoveryCodesResponseToJSON,
    TotpEnrollConfirmRequestFromJSON,
    TotpEnrollConfirmRequestToJSON,
    TotpEnrollStartResponseFromJSON,
    TotpEnrollStartResponseToJSON,
    UserFromJSON,
    UserToJSON,
    VerifyRecoveryCodeRequestFromJSON,
    VerifyRecoveryCodeRequestToJSON,
    VerifyTotpRequestFromJSON,
    VerifyTotpRequestToJSON,
    WhoamiResponseFromJSON,
    WhoamiResponseToJSON,
} from '../models/index';

export interface AuthenticateAndIssueTokenRequest {
    user: User;
}

export interface AuthenticateStartOperationRequest {
    authenticateStartRequest: AuthenticateStartRequest;
}

export interface ConfirmTotpEnrollmentRequest {
    totpEnrollConfirmRequest: TotpEnrollConfirmRequest;
}

export interface CreateAdminUserRequest {
    user: User;
}

export interface VerifyRecoveryCodeOperationRequest {
    verifyRecoveryCodeRequest: VerifyRecoveryCodeRequest;
}

export interface VerifyTotpOperationRequest {
    verifyTotpRequest: VerifyTotpRequest;
}

/**
 * 
 */
export class UserControllerApi extends runtime.BaseAPI {

    /**
     * attempts to authenticate a user and returns an encoded JWT
     * Authenticate user and get token
     */
    async authenticateAndIssueTokenRaw(requestParameters: AuthenticateAndIssueTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling authenticateAndIssueToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/authenticate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters['user']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * attempts to authenticate a user and returns an encoded JWT
     * Authenticate user and get token
     */
    async authenticateAndIssueToken(requestParameters: AuthenticateAndIssueTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authenticateAndIssueTokenRaw(requestParameters, initOverrides);
    }

    /**
     * authenticates username/password and either returns challenge metadata or issues JWT
     * Start authentication flow
     */
    async authenticateStartRaw(requestParameters: AuthenticateStartOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticateStartResponse>> {
        if (requestParameters['authenticateStartRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticateStartRequest',
                'Required parameter "authenticateStartRequest" was null or undefined when calling authenticateStart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/authenticate/start`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticateStartRequestToJSON(requestParameters['authenticateStartRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticateStartResponseFromJSON(jsonValue));
    }

    /**
     * authenticates username/password and either returns challenge metadata or issues JWT
     * Start authentication flow
     */
    async authenticateStart(requestParameters: AuthenticateStartOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticateStartResponse> {
        const response = await this.authenticateStartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * verifies initial OTP and enables TOTP
     * Confirm TOTP enrollment
     */
    async confirmTotpEnrollmentRaw(requestParameters: ConfirmTotpEnrollmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['totpEnrollConfirmRequest'] == null) {
            throw new runtime.RequiredError(
                'totpEnrollConfirmRequest',
                'Required parameter "totpEnrollConfirmRequest" was null or undefined when calling confirmTotpEnrollment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/2fa/totp/enroll/confirm`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TotpEnrollConfirmRequestToJSON(requestParameters['totpEnrollConfirmRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * verifies initial OTP and enables TOTP
     * Confirm TOTP enrollment
     */
    async confirmTotpEnrollment(requestParameters: ConfirmTotpEnrollmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmTotpEnrollmentRaw(requestParameters, initOverrides);
    }

    /**
     * creates an admin user if one does not exist
     * Create Admin User
     */
    async createAdminUserRaw(requestParameters: CreateAdminUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling createAdminUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters['user']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * creates an admin user if one does not exist
     * Create Admin User
     */
    async createAdminUser(requestParameters: CreateAdminUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.createAdminUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * clears the authentication token cookie
     * logout
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * clears the authentication token cookie
     * logout
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(initOverrides);
    }

    /**
     * regenerates one-time recovery codes
     * Regenerate recovery codes
     */
    async regenerateRecoveryCodesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegenerateRecoveryCodesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user/2fa/recovery-codes/regenerate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegenerateRecoveryCodesResponseFromJSON(jsonValue));
    }

    /**
     * regenerates one-time recovery codes
     * Regenerate recovery codes
     */
    async regenerateRecoveryCodes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegenerateRecoveryCodesResponse> {
        const response = await this.regenerateRecoveryCodesRaw(initOverrides);
        return await response.value();
    }

    /**
     * generates a TOTP secret and returns setup metadata
     * Start TOTP enrollment
     */
    async startTotpEnrollmentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TotpEnrollStartResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user/2fa/totp/enroll/start`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TotpEnrollStartResponseFromJSON(jsonValue));
    }

    /**
     * generates a TOTP secret and returns setup metadata
     * Start TOTP enrollment
     */
    async startTotpEnrollment(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TotpEnrollStartResponse> {
        const response = await this.startTotpEnrollmentRaw(initOverrides);
        return await response.value();
    }

    /**
     * verifies recovery code and issues JWT on success
     * Verify recovery code second factor
     */
    async verifyRecoveryCodeRaw(requestParameters: VerifyRecoveryCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['verifyRecoveryCodeRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyRecoveryCodeRequest',
                'Required parameter "verifyRecoveryCodeRequest" was null or undefined when calling verifyRecoveryCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/2fa/verify/recovery-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyRecoveryCodeRequestToJSON(requestParameters['verifyRecoveryCodeRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * verifies recovery code and issues JWT on success
     * Verify recovery code second factor
     */
    async verifyRecoveryCode(requestParameters: VerifyRecoveryCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.verifyRecoveryCodeRaw(requestParameters, initOverrides);
    }

    /**
     * verifies TOTP code and issues JWT on success
     * Verify TOTP second factor
     */
    async verifyTotpRaw(requestParameters: VerifyTotpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['verifyTotpRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyTotpRequest',
                'Required parameter "verifyTotpRequest" was null or undefined when calling verifyTotp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/2fa/verify/totp`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyTotpRequestToJSON(requestParameters['verifyTotpRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * verifies TOTP code and issues JWT on success
     * Verify TOTP second factor
     */
    async verifyTotp(requestParameters: VerifyTotpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.verifyTotpRaw(requestParameters, initOverrides);
    }

    /**
     * returns the username of the logged in user if their token is valid
     * whoami
     */
    async whoamiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WhoamiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user/whoami`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WhoamiResponseFromJSON(jsonValue));
    }

    /**
     * returns the username of the logged in user if their token is valid
     * whoami
     */
    async whoami(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WhoamiResponse> {
        const response = await this.whoamiRaw(initOverrides);
        return await response.value();
    }

}
