#!/usr/bin/env bash
set -exuo pipefail

function escape_ip_for_sed() {
    local ip="$1"
    echo "$ip" | sed 's/[]\.\/|$(){}?+*^]/\\&/g'
}

function escape_key_for_sed() {
    local string="$1"
    echo "$string" | sed 's/\//\\\//g'
}

function remove_peer_from_network() {
  local config_name="$1"
  local client_cidr="$2"
  local client_public_key_name="$3"

  stat "$client_public_key_name"
  local client_public_key=$(cat "$client_public_key_name")

  local escaped_ip=$(escape_ip_for_sed $client_cidr)
  local escaped_key=$(escape_key_for_sed $client_public_key)

  sed -i "/AllowedIPs = $escaped_ip/d" "$config_name"
  sed -i "/PublicKey = $escaped_key/d" "$config_name"
  sed -i "/\[Peer\] \# $escaped_ip/d" "$config_name"
}

function main() {
  set +u
  while true; do
    case "$1" in
      --config-name              ) CONFIG_NAME=$2; shift 2 ;;
      --interface-name          ) INTERFACE_NAME=$2; shift 2;;
      --client-cidr             ) CLIENT_CIDR=$2; shift 2 ;;
      --client-public-key-name  ) PUBLIC_KEY_NAME=$2; shift 2 ;;
      -- ) shift; break ;;
    * ) break ;;
    esac
  done
  set -u

  remove_peer_from_network "$CONFIG_NAME" "$CLIENT_CIDR" "$PUBLIC_KEY_NAME"
  wg syncconf "$INTERFACE_NAME" <(wg-quick strip "$CONFIG_NAME")
  wg-quick down "$INTERFACE_NAME"
  wg-quick up "$INTERFACE_NAME"
}
main "$@"
