/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkClient } from './NetworkClient';
import {
    NetworkClientFromJSON,
    NetworkClientFromJSONTyped,
    NetworkClientToJSON,
    NetworkClientToJSONTyped,
} from './NetworkClient';

/**
 * 
 * @export
 * @interface CreateNetworkClientResponse
 */
export interface CreateNetworkClientResponse {
    /**
     * 
     * @type {NetworkClient}
     * @memberof CreateNetworkClientResponse
     */
    networkClient?: NetworkClient;
}

/**
 * Check if a given object implements the CreateNetworkClientResponse interface.
 */
export function instanceOfCreateNetworkClientResponse(value: object): value is CreateNetworkClientResponse {
    return true;
}

export function CreateNetworkClientResponseFromJSON(json: any): CreateNetworkClientResponse {
    return CreateNetworkClientResponseFromJSONTyped(json, false);
}

export function CreateNetworkClientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNetworkClientResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'networkClient': json['networkClient'] == null ? undefined : NetworkClientFromJSON(json['networkClient']),
    };
}

export function CreateNetworkClientResponseToJSON(json: any): CreateNetworkClientResponse {
    return CreateNetworkClientResponseToJSONTyped(json, false);
}

export function CreateNetworkClientResponseToJSONTyped(value?: CreateNetworkClientResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networkClient': NetworkClientToJSON(value['networkClient']),
    };
}

