/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';

/**
 * 
 * @export
 * @interface CreateNetworkResponse
 */
export interface CreateNetworkResponse {
    /**
     * 
     * @type {Network}
     * @memberof CreateNetworkResponse
     */
    network?: Network;
}

/**
 * Check if a given object implements the CreateNetworkResponse interface.
 */
export function instanceOfCreateNetworkResponse(value: object): value is CreateNetworkResponse {
    return true;
}

export function CreateNetworkResponseFromJSON(json: any): CreateNetworkResponse {
    return CreateNetworkResponseFromJSONTyped(json, false);
}

export function CreateNetworkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNetworkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'network': json['network'] == null ? undefined : NetworkFromJSON(json['network']),
    };
}

export function CreateNetworkResponseToJSON(json: any): CreateNetworkResponse {
    return CreateNetworkResponseToJSONTyped(json, false);
}

export function CreateNetworkResponseToJSONTyped(value?: CreateNetworkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': NetworkToJSON(value['network']),
    };
}

