/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNetworkRequest
 */
export interface CreateNetworkRequest {
    /**
     * unique, alphanumeric, 4-15 character name for the network
     * @type {string}
     * @memberof CreateNetworkRequest
     */
    networkName: string;
    /**
     * CIDR block for the network
     * @type {string}
     * @memberof CreateNetworkRequest
     */
    networkCidr: string;
    /**
     * server listen port for the network
     * @type {number}
     * @memberof CreateNetworkRequest
     */
    networkListenPort: number;
    /**
     * optional free form tag for the network
     * @type {string}
     * @memberof CreateNetworkRequest
     */
    networkTag?: string;
    /**
     * when true, no peer on this network can reach any other peer on it
     * @type {boolean}
     * @memberof CreateNetworkRequest
     */
    peerIsolationEnabled?: boolean;
}

/**
 * Check if a given object implements the CreateNetworkRequest interface.
 */
export function instanceOfCreateNetworkRequest(value: object): value is CreateNetworkRequest {
    if (!('networkName' in value) || value['networkName'] === undefined) return false;
    if (!('networkCidr' in value) || value['networkCidr'] === undefined) return false;
    if (!('networkListenPort' in value) || value['networkListenPort'] === undefined) return false;
    return true;
}

export function CreateNetworkRequestFromJSON(json: any): CreateNetworkRequest {
    return CreateNetworkRequestFromJSONTyped(json, false);
}

export function CreateNetworkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNetworkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'networkName': json['networkName'],
        'networkCidr': json['networkCidr'],
        'networkListenPort': json['networkListenPort'],
        'networkTag': json['networkTag'] == null ? undefined : json['networkTag'],
        'peerIsolationEnabled': json['peerIsolationEnabled'] == null ? undefined : json['peerIsolationEnabled'],
    };
}

export function CreateNetworkRequestToJSON(json: any): CreateNetworkRequest {
    return CreateNetworkRequestToJSONTyped(json, false);
}

export function CreateNetworkRequestToJSONTyped(value?: CreateNetworkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networkName': value['networkName'],
        'networkCidr': value['networkCidr'],
        'networkListenPort': value['networkListenPort'],
        'networkTag': value['networkTag'],
        'peerIsolationEnabled': value['peerIsolationEnabled'],
    };
}

