/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNetworkClientRequest
 */
export interface CreateNetworkClientRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkClientRequest
     */
    clientName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkClientRequest
     */
    clientCidr?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkClientRequest
     */
    clientDns?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkClientRequest
     */
    allowedIps?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkClientRequest
     */
    networkName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkClientRequest
     */
    networkEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkClientRequest
     */
    clientTag?: string;
}

/**
 * Check if a given object implements the CreateNetworkClientRequest interface.
 */
export function instanceOfCreateNetworkClientRequest(value: object): value is CreateNetworkClientRequest {
    if (!('clientName' in value) || value['clientName'] === undefined) return false;
    if (!('networkName' in value) || value['networkName'] === undefined) return false;
    return true;
}

export function CreateNetworkClientRequestFromJSON(json: any): CreateNetworkClientRequest {
    return CreateNetworkClientRequestFromJSONTyped(json, false);
}

export function CreateNetworkClientRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNetworkClientRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientName': json['clientName'],
        'clientCidr': json['clientCidr'] == null ? undefined : json['clientCidr'],
        'clientDns': json['clientDns'] == null ? undefined : json['clientDns'],
        'allowedIps': json['allowedIps'] == null ? undefined : json['allowedIps'],
        'networkName': json['networkName'],
        'networkEndpoint': json['networkEndpoint'] == null ? undefined : json['networkEndpoint'],
        'clientTag': json['clientTag'] == null ? undefined : json['clientTag'],
    };
}

export function CreateNetworkClientRequestToJSON(json: any): CreateNetworkClientRequest {
    return CreateNetworkClientRequestToJSONTyped(json, false);
}

export function CreateNetworkClientRequestToJSONTyped(value?: CreateNetworkClientRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientName': value['clientName'],
        'clientCidr': value['clientCidr'],
        'clientDns': value['clientDns'],
        'allowedIps': value['allowedIps'],
        'networkName': value['networkName'],
        'networkEndpoint': value['networkEndpoint'],
        'clientTag': value['clientTag'],
    };
}

