/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPublicIpResponse
 */
export interface GetPublicIpResponse {
    /**
     * 
     * @type {string}
     * @memberof GetPublicIpResponse
     */
    publicIp?: string;
}

/**
 * Check if a given object implements the GetPublicIpResponse interface.
 */
export function instanceOfGetPublicIpResponse(value: object): value is GetPublicIpResponse {
    return true;
}

export function GetPublicIpResponseFromJSON(json: any): GetPublicIpResponse {
    return GetPublicIpResponseFromJSONTyped(json, false);
}

export function GetPublicIpResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPublicIpResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'publicIp': json['publicIp'] == null ? undefined : json['publicIp'],
    };
}

export function GetPublicIpResponseToJSON(json: any): GetPublicIpResponse {
    return GetPublicIpResponseToJSONTyped(json, false);
}

export function GetPublicIpResponseToJSONTyped(value?: GetPublicIpResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'publicIp': value['publicIp'],
    };
}

