/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';

/**
 * 
 * @export
 * @interface ListNetworksResponse
 */
export interface ListNetworksResponse {
    /**
     * 
     * @type {Array<Network>}
     * @memberof ListNetworksResponse
     */
    networks?: Array<Network>;
    /**
     * 
     * @type {number}
     * @memberof ListNetworksResponse
     */
    nextPage?: number;
}

/**
 * Check if a given object implements the ListNetworksResponse interface.
 */
export function instanceOfListNetworksResponse(value: object): value is ListNetworksResponse {
    return true;
}

export function ListNetworksResponseFromJSON(json: any): ListNetworksResponse {
    return ListNetworksResponseFromJSONTyped(json, false);
}

export function ListNetworksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNetworksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'networks': json['networks'] == null ? undefined : ((json['networks'] as Array<any>).map(NetworkFromJSON)),
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
    };
}

export function ListNetworksResponseToJSON(json: any): ListNetworksResponse {
    return ListNetworksResponseToJSONTyped(json, false);
}

export function ListNetworksResponseToJSONTyped(value?: ListNetworksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networks': value['networks'] == null ? undefined : ((value['networks'] as Array<any>).map(NetworkToJSON)),
        'nextPage': value['nextPage'],
    };
}

