/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Client } from './Client';
import {
    ClientFromJSON,
    ClientFromJSONTyped,
    ClientToJSON,
    ClientToJSONTyped,
} from './Client';

/**
 * 
 * @export
 * @interface ListNetworkClientsResponse
 */
export interface ListNetworkClientsResponse {
    /**
     * 
     * @type {Array<Client>}
     * @memberof ListNetworkClientsResponse
     */
    clients?: Array<Client>;
    /**
     * 
     * @type {number}
     * @memberof ListNetworkClientsResponse
     */
    nextPage?: number;
}

/**
 * Check if a given object implements the ListNetworkClientsResponse interface.
 */
export function instanceOfListNetworkClientsResponse(value: object): value is ListNetworkClientsResponse {
    return true;
}

export function ListNetworkClientsResponseFromJSON(json: any): ListNetworkClientsResponse {
    return ListNetworkClientsResponseFromJSONTyped(json, false);
}

export function ListNetworkClientsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNetworkClientsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clients': json['clients'] == null ? undefined : ((json['clients'] as Array<any>).map(ClientFromJSON)),
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
    };
}

export function ListNetworkClientsResponseToJSON(json: any): ListNetworkClientsResponse {
    return ListNetworkClientsResponseToJSONTyped(json, false);
}

export function ListNetworkClientsResponseToJSONTyped(value?: ListNetworkClientsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clients': value['clients'] == null ? undefined : ((value['clients'] as Array<any>).map(ClientToJSON)),
        'nextPage': value['nextPage'],
    };
}

