/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateNetworkClientRequest
 */
export interface UpdateNetworkClientRequest {
    /**
     * name of the network the client belongs to
     * @type {string}
     * @memberof UpdateNetworkClientRequest
     */
    networkName: string;
    /**
     * name of the client to update
     * @type {string}
     * @memberof UpdateNetworkClientRequest
     */
    clientName: string;
    /**
     * optional free form tag for the client
     * @type {string}
     * @memberof UpdateNetworkClientRequest
     */
    clientTag?: string;
    /**
     * when true this client can neither reach nor be reached by any other peer on the network. its traffic still routes through the server to the internet
     * @type {boolean}
     * @memberof UpdateNetworkClientRequest
     */
    peerIsolationEnabled?: boolean;
}

/**
 * Check if a given object implements the UpdateNetworkClientRequest interface.
 */
export function instanceOfUpdateNetworkClientRequest(value: object): value is UpdateNetworkClientRequest {
    if (!('networkName' in value) || value['networkName'] === undefined) return false;
    if (!('clientName' in value) || value['clientName'] === undefined) return false;
    return true;
}

export function UpdateNetworkClientRequestFromJSON(json: any): UpdateNetworkClientRequest {
    return UpdateNetworkClientRequestFromJSONTyped(json, false);
}

export function UpdateNetworkClientRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNetworkClientRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'networkName': json['networkName'],
        'clientName': json['clientName'],
        'clientTag': json['clientTag'] == null ? undefined : json['clientTag'],
        'peerIsolationEnabled': json['peerIsolationEnabled'] == null ? undefined : json['peerIsolationEnabled'],
    };
}

export function UpdateNetworkClientRequestToJSON(json: any): UpdateNetworkClientRequest {
    return UpdateNetworkClientRequestToJSONTyped(json, false);
}

export function UpdateNetworkClientRequestToJSONTyped(value?: UpdateNetworkClientRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networkName': value['networkName'],
        'clientName': value['clientName'],
        'clientTag': value['clientTag'],
        'peerIsolationEnabled': value['peerIsolationEnabled'],
    };
}

