/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
    NetworkToJSONTyped,
} from './Network';

/**
 * 
 * @export
 * @interface UpdateNetworkResponse
 */
export interface UpdateNetworkResponse {
    /**
     * 
     * @type {Network}
     * @memberof UpdateNetworkResponse
     */
    network?: Network;
}

/**
 * Check if a given object implements the UpdateNetworkResponse interface.
 */
export function instanceOfUpdateNetworkResponse(value: object): value is UpdateNetworkResponse {
    return true;
}

export function UpdateNetworkResponseFromJSON(json: any): UpdateNetworkResponse {
    return UpdateNetworkResponseFromJSONTyped(json, false);
}

export function UpdateNetworkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNetworkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'network': json['network'] == null ? undefined : NetworkFromJSON(json['network']),
    };
}

export function UpdateNetworkResponseToJSON(json: any): UpdateNetworkResponse {
    return UpdateNetworkResponseToJSONTyped(json, false);
}

export function UpdateNetworkResponseToJSONTyped(value?: UpdateNetworkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'network': NetworkToJSON(value['network']),
    };
}

