/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NetworkClient } from './NetworkClient';
import {
    NetworkClientFromJSON,
    NetworkClientFromJSONTyped,
    NetworkClientToJSON,
    NetworkClientToJSONTyped,
} from './NetworkClient';

/**
 * 
 * @export
 * @interface UpdateNetworkClientResponse
 */
export interface UpdateNetworkClientResponse {
    /**
     * 
     * @type {NetworkClient}
     * @memberof UpdateNetworkClientResponse
     */
    networkClient?: NetworkClient;
}

/**
 * Check if a given object implements the UpdateNetworkClientResponse interface.
 */
export function instanceOfUpdateNetworkClientResponse(value: object): value is UpdateNetworkClientResponse {
    return true;
}

export function UpdateNetworkClientResponseFromJSON(json: any): UpdateNetworkClientResponse {
    return UpdateNetworkClientResponseFromJSONTyped(json, false);
}

export function UpdateNetworkClientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNetworkClientResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'networkClient': json['networkClient'] == null ? undefined : NetworkClientFromJSON(json['networkClient']),
    };
}

export function UpdateNetworkClientResponseToJSON(json: any): UpdateNetworkClientResponse {
    return UpdateNetworkClientResponseToJSONTyped(json, false);
}

export function UpdateNetworkClientResponseToJSONTyped(value?: UpdateNetworkClientResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'networkClient': NetworkClientToJSON(value['networkClient']),
    };
}

